version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: development
      POSTGRES_DB: wallets
    volumes:
      - /var/data/wallets/database:/var/lib/postgresql/data

  wallets:
    build:
      context: .
    working_dir: /app
    environment:
      DATABASE_URL: postgres://admin:development@postgres:5432/wallets
      DEBUG: "TRUE"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    links:
      - postgres

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/general.conf:/etc/nginx/general.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./logs:/var/log/wallets
      - ./static:/var/www/wallets/static:ro
      - ./media:/var/www/wallets/media:ro
    links:
      - wallets
    depends_on:
      - wallets
