version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: development
      POSTGRES_DB: wallets
    volumes:
      - /var/data/wallets/database:/var/lib/postgresql/data

  wallets:
    image: docker.pkg.github.com/pablo-moreno/wallets:latest
    working_dir: /app
    environment:
      DATABASE_URL: postgres://admin:development@postgres:5432/wallets
      DEBUG: "TRUE"
    entrypoint: ["uvicorn", "--workers", "1", "--host", "0.0.0.0", "--port", "8000", "config.asgi:application"]
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static/:/app/static
    depends_on:
      - postgres
    links:
      - postgres

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/general.conf:/etc/nginx/general.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./logs/:/var/log/wallets
      - ./static:/var/www/wallets/static:ro
      - ./media:/var/www/wallets/media:ro
    links:
      - wallets
    depends_on:
      - wallets
