# Generated by Django 3.2 on 2021-04-17 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import wallets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=250)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], db_index=True, default=1)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Deposit'), (2, 'Debit')], db_index=True, default=2)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
            bases=(models.Model, wallets.models.TransactionStatusChoicesMixin, wallets.models.TransactionTypeChoicesMixin),
        ),
        migrations.CreateModel(
            name='CustomerWallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_wallets', to=settings.AUTH_USER_MODEL)),
                ('wallets', models.ManyToManyField(to='wallets.Wallet')),
            ],
            options={
                'verbose_name': 'Customer wallets',
                'verbose_name_plural': 'Customer wallets',
            },
        ),
        migrations.CreateModel(
            name='BusinessWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='business_wallet', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Business wallet',
                'verbose_name_plural': 'Business wallets',
            },
        ),
    ]
