# Generated by Django 3.2 on 2021-04-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_businesscustomers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='customer',
        ),
    ]
