name: Docker

on:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
      - '*'

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: wallets
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker-compose --file docker-compose.test.yml run -e CODECOV_TOKEN=$CODECOV_TOKEN wallets bash runtests.sh

  # Push image to GitHub Packages.
  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/pablo-moreno/wallets/wallets:latest

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/pablo-moreno/wallets/wallets
          docker push $IMAGE_ID:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            docker pull docker.pkg.github.com/pablo-moreno/wallets:latest
            docker service update --force wallets_wallets
            docker exec $(docker ps -q -f name=wallets_wallet) python manage.py migrate
            docker exec $(docker ps -q -f name=wallets_wallet) python manage.py collectstatic --no-input
